/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  dpattas
 * Created: Jul 21, 2017
 */

CREATE TABLE APP_USER (
EMAIL VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
PASSWORD VARCHAR(255),
DATE_REGISTERED DATE,
USER_ROLE SMALLINT,
PRIMARY KEY (EMAIL)
);

CREATE TABLE CATEGORY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255)
);

CREATE TABLE SKILLS_MAP (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STUDENT_EMAIL VARCHAR(255) NOT NULL REFERENCES APP_USER(EMAIL) ON DELETE CASCADE,
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
SKILL_LEVEL INTEGER NOT NULL
);

CREATE TABLE ACTIVITY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255),
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
ENABLED BOOLEAN DEFAULT FALSE
);

CREATE TABLE GROUPS
(
   EMAIL varchar(255) NOT NULL,
   GROUP_NAME varchar(50) NOT NULL,
   FOREIGN KEY (EMAIL) REFERENCES APP_USER(EMAIL) ON DELETE CASCADE,
  PRIMARY KEY(EMAIL,GROUP_NAME)
);

CREATE TABLE ACTIVITIES_MAP (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STUDENT_EMAIL VARCHAR(255) REFERENCES APP_USER(EMAIL) ON DELETE CASCADE,
ACTIVITY BIGINT REFERENCES ACTIVITY(ID) ON DELETE CASCADE,
LOGGED BOOLEAN DEFAULT FALSE,
ANSWER INTEGER,
DATE_ANSWERED DATE,
DATE_ENABLED DATE,
DATE_DISABLED DATE,
NEW_SKILL_LEVEL INTEGER,
ENABLED BOOLEAN DEFAULT TRUE
);

ALTER TABLE APP_USER ADD COLUMN NICKNAME VARCHAR(255);
ALTER TABLE ACTIVITIES_MAP ADD COLUMN ENABLED BOOLEAN DEFAULT TRUE;