/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  dpattas
 * Created: Jul 21, 2017
 */

CREATE TABLE APP_USER (
EMAIL VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
PASSWORD VARCHAR(255),
USER_ROLE SMALLINT,
PRIMARY KEY (EMAIL)
);

CREATE TABLE CATEGORY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255)
);

CREATE TABLE SKILLS_MAP (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STUDENT_EMAIL VARCHAR(255) NOT NULL REFERENCES APP_USER(EMAIL) ON DELETE CASCADE,
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
SKILL_LEVEL INTEGER NOT NULL
);

CREATE TABLE ACTIVITY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255),
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE
);

CREATE TABLE GROUPS
(
   EMAIL varchar(255) NOT NULL,
   GROUP_NAME varchar(50) NOT NULL,
   FOREIGN KEY (EMAIL) REFERENCES APP_USER(EMAIL) ON DELETE CASCADE,
  PRIMARY KEY(EMAIL,GROUP_NAME)
);

ALTER TABLE GROUPS ADD COLUMN EMAIL VARCHAR(255) REFERENCES APP_USER(EMAIL) ON DELETE CASCADE;
