/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  dpattas
 * Created: Jul 21, 2017
 */

CREATE TABLE STUDENT (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255)
);

CREATE TABLE SKILLS_MAP (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STUDENT_ID BIGINT NOT NULL REFERENCES STUDENT(ID),
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
SKILL_LEVEL INTEGER NOT NULL
);

CREATE TABLE ACTIVITY (
ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITLE VARCHAR(255),
CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE
);
